name: Deploy to InterServer

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.INTERSERVER_PRIVATE_KEY }}

      - name: Deploy via SCP
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.INTERSERVER_USER }}@${{ secrets.INTERSERVER_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"
          scp -r * ${{ secrets.INTERSERVER_USER }}@${{ secrets.INTERSERVER_HOST }}:${{ secrets.DEPLOY_PATH }}
